export const ActionType =
    {
        LANG_CHANGE: 'LANG_CHANGE',

        USER_CREATE: 'USER_CREATE',
        USER_CREATE_REQ: 'USER_CREATE_REQ',
        USER_VERIFY_EMAIL: 'USER_VERIFY_EMAIL',
        USER_SIGN_UP: 'USER_SIGN_UP',
        USER_SIGN_IN: 'USER_SIGN_IN',

        ALERT_ERR_API: 'ALERT_ERR_API',
        ALERT_INFO: 'ALERT_INFO',

        DLG_LOGIN: 'DLG_LOGIN',
        DLG_REGISTER_DIALOG_1: 'DLG_REGISTER_DIALOG_1',
        DLG_REGISTER_DIALOG_2: 'DLG_REGISTER_DIALOG_2',
        DLG_REGISTER_DIALOG_2_OK: 'DLG_REGISTER_DIALOG_2_OK',
        DLG_REGISTER_DIALOG_3: 'DLG_REGISTER_DIALOG_3',
        DLG_REGISTERREQ_DIALOG_2: 'DLG_REGISTERREQ_DIALOG_2',
        DLG_REGISTERREQ_DIALOG_2_OK: 'DLG_REGISTERREQ_DIALOG_2_OK',
        DLG_UPLOAD_IMAGE_DIALOG: 'DLG_UPLOAD_IMAGE_DIALOG',

        SESSION_REFRESH: 'SESSION_REFRESH',
        PROFILE_REFRESH: 'PROFILE_REFRESH',

        ARTIST_CREATE: 'ARTIST_CREATE',
        ARTIST_UPDATE: 'ARTIST_UPDATE',

        VALUE_GET_ALL: 'VALUE_GET_ALL',

        PICTURE_CREATE: 'PICTURE_CREATE',
        PICTURE_UPDATE: 'PICTURE_UPDATE',

        CATALOG_GET_ALL: 'CATALOG_GET_ALL',
        CATALOG_GET_ONE: 'CATALOG_GET_ONE',
        CATALOG_REFRESH: 'CATALOG_REFRESH',

        TMP_DLG_LANGUAGE_SELECT: 'TMP_DLG_LANGUAGE_SELECT',
        TMP_ALERT_INFO: 'TMP_ALERT_INFO',

    }

